#!/usr/bin/env -S uv --quiet run --script

# /// script
# requires-python = ">=3.10"
# ///

"""Runs the vale-ai-tells prose linter against files or draft text.

vale-ai-tells (https://github.com/tbhb/vale-ai-tells) is a Vale style package,
not a standalone tool. Using it normally means adding a `.vale.ini` to a
project and running `vale sync` there. This script keeps that setup in a cache
directory of its own instead, so any text can be linted without adding Vale
configuration to the repository being worked in.

Subcommands:
    check <path>...        Lint files. Exit 1 when Vale reports alerts.
    check-text             Lint prose on stdin as if it were a Markdown file.
    sync [--force]         Write the config and download the styles.
    config-path            Print the path of the generated config file.
    status                 Report where things stand: Vale, config, styles.

Both `check` commands accept `--output=<fmt>`, passed on to Vale (`line`, the
default here, `CLI`, or `JSON`).
"""

import hashlib
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

# The release of vale-ai-tells this plugin pins. Bumping it makes the next run
# re-download the styles, because sync compares this string against the stamp
# file written by the previous sync.
PACKAGE_VERSION = "v1.31.0"

# Only the prose style. vale-ai-tells also ships `ai-tells-commits` (commit
# message rules) and `ai-tells-experimental` (structural rules its author
# marks as opt-in and noisy); neither is installed here.
PACKAGE_NAME = "ai-tells"

RELEASE_URL = (
    "https://github.com/tbhb/vale-ai-tells/releases/download/"
    f"{PACKAGE_VERSION}/{PACKAGE_NAME}.zip"
)

DEFAULT_OUTPUT = "line"

STAMP_NAME = ".synced-version"

# Records what the last generated vale.ini looked like, so a later run can tell
# an untouched config apart from one the user has tuned.
CONFIG_HASH_NAME = ".config-hash"

VALE_MISSING = """\
Vale is not installed, so vale-ai-tells has nothing to run.

    brew install vale

Then run this command again."""

CONFIG_STALE = """\
Note: {path} does not match the config this version of ai-tells generates, and \
may hold rule lines you added, so it is being left as it is. To replace it, \
save any lines you want to keep and run: {script} sync --force"""


def home_dir() -> Path:
    """Return the directory holding the generated config and the styles.

    $AI_TELLS_HOME overrides it, which is what the tests use. Otherwise it
    follows $XDG_CACHE_HOME, then ~/.cache.
    """
    override = os.environ.get("AI_TELLS_HOME")
    if override:
        return Path(override).expanduser()
    xdg = os.environ.get("XDG_CACHE_HOME")
    base = Path(xdg).expanduser() if xdg else Path.home() / ".cache"
    return base / "vale-ai-tells"


def config_path(home: Path) -> Path:
    return home / "vale.ini"


def styles_path(home: Path) -> Path:
    return home / "styles"


def stamp_path(home: Path) -> Path:
    return home / STAMP_NAME


def config_hash_path(home: Path) -> Path:
    return home / CONFIG_HASH_NAME


def render_config(home: Path) -> str:
    """Build the `.vale.ini` contents for this cache directory.

    StylesPath is absolute so that Vale finds the styles no matter which
    directory it runs from.

    Every rule in the package is set to `error` level, so MinAlertLevel cannot
    filter anything out. Turning a rule off means naming it below the `[*]`
    section, so an edited config is left alone.
    """
    return f"""\
# Generated by the ai-tells plugin. Edit freely: an edited file is left as it
# is, and only `sync --force` overwrites it.
#
# To silence a rule, add a line below the [*] section, e.g.:
#     ai-tells.EmDashUsage = NO
# The rule list is at https://github.com/tbhb/vale-ai-tells#rules-included

StylesPath = {styles_path(home)}
MinAlertLevel = suggestion

Packages = {RELEASE_URL}

# Every file, not only Markdown. Vale chooses a parser from the extension, so a
# source file it recognises has its comments and docstrings linted while the
# code around them is left alone. An extension it has no parser for is read as
# plain prose from the first line to the last.
[*]
BasedOnStyles = {PACKAGE_NAME}
"""


def synced_version(home: Path) -> str | None:
    """Return the package version the styles on disk came from, if any."""
    if not (styles_path(home) / PACKAGE_NAME).is_dir():
        return None
    try:
        return stamp_path(home).read_text(encoding="utf-8").strip()
    except OSError:
        return None


def needs_sync(home: Path) -> bool:
    return synced_version(home) != PACKAGE_VERSION


def require_vale() -> str:
    vale = shutil.which("vale")
    if not vale:
        sys.exit(VALE_MISSING)
    return vale


def digest(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def config_is_untouched(home: Path) -> bool:
    """True when vale.ini still matches the last config this script generated."""
    try:
        recorded = config_hash_path(home).read_text(encoding="utf-8").strip()
        return recorded == digest(config_path(home).read_text(encoding="utf-8"))
    except OSError:
        return False


def config_is_stale(home: Path) -> bool:
    """True when vale.ini is out of date and only the user can replace it.

    A config the user has tuned outranks a plugin update, so a mismatch here is
    reported rather than fixed.
    """
    if not config_path(home).exists() or config_is_untouched(home):
        return False
    try:
        return config_path(home).read_text(encoding="utf-8") != render_config(home)
    except OSError:
        return False


def write_config(home: Path, force: bool = False) -> bool:
    """Bring the config up to date. Return True if it was written.

    An update to this script changes the template, and an untouched config is
    rewritten so that the change reaches installs that already have one. A
    config with the user's own rule lines in it is kept, since `--force` is the
    only way to say those lines can go.
    """
    home.mkdir(parents=True, exist_ok=True)
    path = config_path(home)
    wanted = render_config(home)
    if path.exists() and not force:
        if path.read_text(encoding="utf-8") == wanted or not config_is_untouched(home):
            return False
    path.write_text(wanted, encoding="utf-8")
    config_hash_path(home).write_text(digest(wanted) + "\n", encoding="utf-8")
    return True


def run_sync(home: Path, force: bool = False) -> None:
    """Download the styles into the cache directory.

    `vale sync` wipes and rewrites StylesPath, so the stamp is only written
    after it succeeds. A failed sync leaves the stamp stale and the next run
    tries again.
    """
    vale = require_vale()
    write_config(home, force=force)
    result = subprocess.run(
        [vale, f"--config={config_path(home)}", "sync"],
        cwd=home,
    )
    if result.returncode != 0:
        sys.exit(result.returncode)
    stamp_path(home).write_text(PACKAGE_VERSION + "\n", encoding="utf-8")


def stale_config_note(home: Path) -> str:
    return CONFIG_STALE.format(path=config_path(home), script=Path(__file__).name)


def ensure_ready(home: Path) -> None:
    require_vale()
    if needs_sync(home):
        print(
            f"Downloading vale-ai-tells {PACKAGE_VERSION} (one time)...",
            file=sys.stderr,
        )
        run_sync(home)
    else:
        write_config(home)
    if config_is_stale(home):
        print(stale_config_note(home), file=sys.stderr)


def split_output_flag(argv: list[str]) -> tuple[str, list[str]]:
    """Pull `--output=<fmt>` / `--output <fmt>` out of the argument list."""
    output = DEFAULT_OUTPUT
    rest: list[str] = []
    i = 0
    while i < len(argv):
        arg = argv[i]
        if arg.startswith("--output="):
            output = arg.split("=", 1)[1]
        elif arg == "--output":
            if i + 1 >= len(argv):
                sys.exit("--output needs a value (line, CLI, or JSON)")
            output = argv[i + 1]
            i += 1
        else:
            rest.append(arg)
        i += 1
    return output, rest


def run_vale(home: Path, output: str, paths: list[str]) -> subprocess.CompletedProcess:
    vale = require_vale()
    return subprocess.run(
        [vale, f"--config={config_path(home)}", f"--output={output}", *paths],
        capture_output=True,
        text=True,
    )


def relabel(text: str, real_path: str, label: str) -> str:
    """Replace a temporary file's path in Vale's output with a readable label."""
    return text.replace(real_path, label)


def cmd_check(home: Path, argv: list[str]) -> int:
    output, paths = split_output_flag(argv)
    if not paths:
        sys.exit("check needs at least one file path")
    missing = [p for p in paths if not Path(p).exists()]
    if missing:
        sys.exit("No such file: " + ", ".join(missing))
    ensure_ready(home)
    result = run_vale(home, output, paths)
    sys.stdout.write(result.stdout)
    sys.stderr.write(result.stderr)
    return result.returncode


def cmd_check_text(home: Path, argv: list[str]) -> int:
    output, rest = split_output_flag(argv)
    if rest:
        sys.exit("check-text takes no file arguments; it reads stdin")
    text = sys.stdin.read()
    if not text.strip():
        sys.exit("check-text got no text on stdin")
    ensure_ready(home)
    # Vale picks a parser by file extension, so the draft reaches it named
    # `draft.md`. Markdown is what loose prose already is, and it keeps stdin
    # away from the comment-extracting parsers the source formats get.
    with tempfile.TemporaryDirectory() as tmpdir:
        draft = Path(tmpdir) / "draft.md"
        draft.write_text(text, encoding="utf-8")
        result = run_vale(home, output, [str(draft)])
        sys.stdout.write(relabel(result.stdout, str(draft), "draft"))
        sys.stderr.write(relabel(result.stderr, str(draft), "draft"))
        return result.returncode


def cmd_sync(home: Path, argv: list[str]) -> int:
    force = "--force" in argv
    run_sync(home, force=force)
    print(f"vale-ai-tells {PACKAGE_VERSION} synced to {styles_path(home)}")
    return 0


def cmd_config_path(home: Path, _argv: list[str]) -> int:
    print(config_path(home))
    return 0


def cmd_status(home: Path, _argv: list[str]) -> int:
    vale = shutil.which("vale")
    print(f"vale:    {vale or 'NOT INSTALLED (brew install vale)'}")
    print(f"config:  {config_path(home)}"
          f"{'' if config_path(home).exists() else ' (not written yet)'}")
    current = synced_version(home)
    if current is None:
        print(f"styles:  not downloaded yet (want {PACKAGE_VERSION})")
    elif current != PACKAGE_VERSION:
        print(f"styles:  {current} on disk, {PACKAGE_VERSION} wanted — run sync")
    else:
        print(f"styles:  {current} at {styles_path(home)}")
    if config_is_stale(home):
        print()
        print(stale_config_note(home))
    return 0


COMMANDS = {
    "check": cmd_check,
    "check-text": cmd_check_text,
    "sync": cmd_sync,
    "config-path": cmd_config_path,
    "status": cmd_status,
}


def main(argv: list[str]) -> int:
    if not argv or argv[0] in ("-h", "--help", "help"):
        print(__doc__)
        return 0
    command, *rest = argv
    handler = COMMANDS.get(command)
    if handler is None:
        sys.exit(f"Unknown command: {command}\n\n{__doc__}")
    return handler(home_dir(), rest)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
